# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        our_db_provider:
            entity:
                class: PPPCanBundle:Usuario
                property: usuario



    firewalls:
        default:
            anonymous: ~
            http_basic: ~ 
            form_login:
                login_path: /login
                check_path: /login_check
                # field names for the username and password fields:
                username_parameter: _usuario
                password_parameter: _contrasena 
                # default_target_path: default_security_target
                # always_use_default_target_path: true
            logout:
                path:   /logout
                target: /login
              
               
        # disables authentication for assets and the profiler, adapt it according to your needs


        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~

    encoders:
        PPP\CanBundle\Entity\Usuario:
            algorithm: bcrypt
            cost: 12

    

    #access_control:
    #    - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    #    - { path: ^/$, roles: IS_AUTHENTICATED_FULLY }
    #    - { path: ^/ataque/add, roles: [ ROLE_PROPIETARIO ] }        
    #    - { path: ^/ataque/index, roles: [ ROLE_PROPIETARIO ] }        
    #    - { path: ^/checklist/index, roles: [ ROLE_ZOOTECNISTA, ROLE_COORDINADOR, ROLE_JEFE_DEPARTAMENTO ] }
    #    - { path: ^/mascota/add, roles: [ ROLE_PROPIETARIO ] }
    #    - { path: ^/mascota/index, roles: [ ROLE_PROPIETARIO ] }
    #    - { path: ^/mascota/index1, roles: [ ROLE_ZOOTECNISTA, ROLE_COORDINADOR, ROLE_JEFE_DEPARTAMENTO ] }                
    #    - { path: ^/propietario/index, roles: [ ROLE_ZOOTECNISTA, ROLE_COORDINADOR, ROLE_JEFE_DEPARTAMENTO ] }
    #    - { path: ^/radicado/add, roles: [ ROLE_PROPIETARIO ] }
    #    - { path: ^/radicado/index, roles: [ ROLE_ZOOTECNISTA, ROLE_COORDINADOR, ROLE_JEFE_DEPARTAMENTO ] }        
    #    - { path: ^/raza/add, roles: [ ROLE_ZOOTECNISTA, ROLE_COORDINADOR ] }        
    #    - { path: ^/raza/index, roles: [ ROLE_ZOOTECNISTA, ROLE_COORDINADOR ] }                
    #    - { path: ^/reportes, roles: [ ROLE_COORDINADOR, ROLE_JEFE_DEPARTAMENTO ] }
    #    - { path: ^/usuario/add, roles: [ ROLE_JEFE_DEPARTAMENTO ] }        
    #    - { path: ^/usuario/index, roles: [ ROLE_JEFE_DEPARTAMENTO ] }                
    #    - { path: ^/reportes/, roles: [ ROLE_JEFE_DEPARTAMENTO ] }                
    #    - { path: ^/reportes/usuarios, roles: [ ROLE_JEFE_DEPARTAMENTO ] } 
    #    - { path: ^/reportes/perros, roles: [ ROLE_JEFE_DEPARTAMENTO ] }                

