ppp_mascota_view:
  path:     /view/{id}
  defaults: { _controller: PPPCanBundle:Mascota:view }

ppp_mascota_index:
    path:     /index/{idUsuario}
    defaults: { _controller: PPPCanBundle:Mascota:index }

ppp_mascota_index1:
    path:     /index1
    defaults: { _controller: PPPCanBundle:Mascota:index1 }


ppp_mascota_add:
    path:     /add
    defaults: { _controller: PPPCanBundle:Mascota:add }

ppp_mascota_create:
    path:     /create
    defaults: { _controller: PPPCanBundle:Mascota:create }
    methods: POST 

ppp_mascota_redirect_add:
  path: /create
  defaults:
    _controller: PPPCanBundle:Mascota:add
    path: /add
    permanent: true

ppp_mascota_edit:
    path: /edit/{id}
    defaults: {_controller: PPPCanBundle:Mascota:edit }

ppp_mascota_update:
    path: /update/{id}
    defaults: {_controller: PPPCanBundle:Mascota:update }
    methods: [POST, PUT]    

ppp_mascota_redirect_edit:
  path: /update/{id}
  defaults:
    _controller: PPPCanBundle:Mascota:edit
    path: /edit/{id}
    permanent: true     

ppp_mascota_delete:
  path:     /delete/{id}
  defaults: { _controller: PPPCanBundle:Mascota:delete }
  methods: [POST, DELETE]
