ppp_propietario_index:
    path:     /index
    defaults: { _controller: PPPCanBundle:Propietario:index }

ppp_propietario_view:
  path:     /view/{id}
  defaults: { _controller: PPPCanBundle:Propietario:view }
