ppp_raza_index:
    path:     /index
    defaults: { _controller: PPPCanBundle:Raza:index }

ppp_raza_add:
    path:     /add
    defaults: { _controller: PPPCanBundle:Raza:add }

ppp_raza_create:
    path:     /create
    defaults: { _controller: PPPCanBundle:Raza:create }
    methods: POST 

ppp_raza_redirect_add:
  path: /create
  defaults:
    _controller: PPPCanBundle:Raza:add
    path: /add
    permanent: true

ppp_raza_edit:
    path: /edit/{id}
    defaults: {_controller: PPPCanBundle:Raza:edit }

ppp_raza_update:
    path: /update/{id}
    defaults: {_controller: PPPCanBundle:Raza:update }
    methods: [POST, PUT]    

ppp_raza_redirect_edit:
  path: /update/{id}
  defaults:
    _controller: PPPCanBundle:Raza:edit
    path: /edit/{id}
    permanent: true     

ppp_raza_delete:
  path:     /delete/{id}
  defaults: { _controller: PPPCanBundle:Raza:delete }
  methods: [POST, DELETE]
