<?php

namespace PPP\CanBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RadicadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RadicadoRepository extends EntityRepository
{
}
